---
- hosts: open_vpn
  remote_user: ubuntu
  become: yes
  become_user: root
  vars:
    ansible_ssh_private_key_file: "~/.ssh/open_vpn_ssh_key"
  roles:
    - admins
    - apt
    - default_config
    - iptables
    - open_vpn
